# API Specification for JUDO Connectivity Module
api_version: "3.13" # Note: Only parts of the API are listed / supported
base_url: "/api/rest"

# Common response patterns that can be reused
response_patterns:
  hex_value:
    encoding: "hex"
    decode_method: "decode_hex_value"
    description: "Hex value representing a numeric value"

  water_volume:
    encoding: "hex"
    decode_method: "decode_water_volume"
    description: "Hex value representing water volume (converts from liters to m³)"

  timestamp:
    encoding: "hex"
    decode_method: "decode_timestamp"
    description: "Hex value representing a UNIX timestamp"

  version:
    encoding: "hex"
    decode_method: "decode_version"
    description: "Hex value representing version (2-letter, 2-minor, 2-major)"

  datetime_bytes:
    encoding: "hex"
    decode_method: "decode_datetime_bytes"
    description: "6 bytes representing date and time components"

parameter_patterns:
  hex_date:
    description: "Date in hex format DDMMYY"
    validation: "^[0-9A-F]{6}$"
    encode_method: "encode_hex_date"

  hex_week:
    description: "Week number in hex"
    validation: "^[0-9A-F]{2}$"
    encode_method: "encode_hex_week"

  hex_month:
    description: "Month number in hex"
    validation: "^[0-9A-F]{2}$"
    encode_method: "encode_hex_month"

  hex_year:
    description: "Year (last 2 digits) in hex"
    validation: "^[0-9A-F]{2}$"
    encode_method: "encode_hex_year"

# Error responses
error_responses:
  400:
    description: "Bad Request"
    possible_causes: "No arguments present or command not allowed."
  401:
    description: "Authentication failed"
    possible_causes: "Invalid credentials or session expired."
  404:
    description: "Endpoint not found"
    possible_causes: "The requested API endpoint does not exist."
  429:
    description: "Too Many Requests"
    possible_causes: "Request rate limit exceeded; retry after 2 seconds."
  500:
    description: "Internal Server Error"
    possible_causes: "An unexpected error occurred on the server, or arguments are incorrect or too long."
  general_errors:
    RestApiErrorInvalidArgument:
      code: -1
      description: "Invalid argument"
    RestApiErrorInvalidMessage:
      code: -2
      description: "Invalid message"
    RestApiErrorBufferTooSmall:
      code: -3
      description: "Buffer too small"
    RestApiErrorBufferBusy:
      code: -4
      description: "Buffer is busy"
  device_control_errors:
    error_response_prefix: 0xFF
    communication_errors:
      - code: 0
        description: "Not enough bytes received"
      - code: 1
        description: "Internal checksum is incorrect"
      - code: 2
        description: "Data (bytes 0,1) are not as expected"
      - code: 3
        description: "Function code (bytes 2,3) is not as expected"
      - code: 4
        description: "An error response was received"
      - code: 5
        description: "A formally correct response was received"
    examples:
      INFO_NO_HEADER:
        description: "Checksum is incorrect"
        response: "FF0001"